<center>
<p><img src="https://mcd.unison.mx/wp-content/themes/awaken/img/logo_mcd.png" width="150">
</p>



# Curso *Ingeniería de Características*

##  Tarea 1
### Descargando datos con python
   
#### Eliud Rodríguez

</center>

# Downloading data

In [1]:
# Importing dataframes
import os  # Para manejo de archivos y directorios
import urllib.request # Una forma estandard de descargar datos
import datetime # Fecha de descarga
import pandas as pd # Solo para ver el archivo descargado
import zipfile # Descompresión de archivos

In [2]:
# pwd
print(os.getcwd())

#  Estos son los datos que vamos a descargar y donde vamos a guardarlos

# Datos de casos de covid en México el día 18 de agosto de 2022
COVID_url_1 = "https://datosabiertos.salud.gob.mx/gobmx/salud/datos_abiertos/historicos/2022/08/datos_abiertos_covid19_18.08.2022.zip"
COVID_archivo_1 = "COVID19_MEX_18_08_22.zip"
subdir_1 = "./data/COVID19_MEX_18_08_22_"
info_1 = """
        18 de agosto de 2022
        Recolección de información estadística de los casos del virus COVID 19 presentados en México,
        contiene diferentes características sobre los pacientes como son el sexo, municipio, fecha de 
        sintomas, edad, embarazo, diabetes, obesidad, entre muchas otras.
        """ 

# Datos de casos de covid en México el día 18 de septiembre de 2022
COVID_url_2 = "https://datosabiertos.salud.gob.mx/gobmx/salud/datos_abiertos/historicos/2022/09/datos_abiertos_covid19_18.09.2022.zip"
COVID_archivo_2 = "COVID19_MEX_18_09_22.zip"
subdir_2 = "./data/COVID19_MEX_18_09_22_"
info_2 = """
        18 de septiembre de 2022
        Recolección de información estadística de los casos del virus COVID 19 presentados en México,
        contiene diferentes características sobre los pacientes como son el sexo, municipio, fecha de 
        sintomas, edad, embarazo, diabetes, obesidad, entre muchas otras.
        """ 

# Datos de casos de covid en México el día 18 de octubre de 2022
COVID_url_3 = "https://datosabiertos.salud.gob.mx/gobmx/salud/datos_abiertos/datos_abiertos_covid19.zip"
COVID_archivo_3 = "COVID19_MEX_18_10_22.zip"
subdir_3 = "./data/COVID19_MEX_18_10_22_"
info_3 = """
        18 de octubre de 2022
        Recolección de información estadística de los casos del virus COVID 19 presentados en México,
        contiene diferentes características sobre los pacientes como son el sexo, municipio, fecha de 
        sintomas, edad, embarazo, diabetes, obesidad, entre muchas otras.
        """

c:\Users\eliud\projects\MCD\Feature_Engineering\HW4. Proyecto_1

In [3]:
# Function to download the datasets
def downloading_dataset(dataset_url, dataset_name, dataset_subdir, info_text):
    if not os.path.exists(dataset_name):
        if not os.path.exists(dataset_subdir):
            os.makedirs(dataset_subdir)
        urllib.request.urlretrieve(dataset_url, dataset_subdir + dataset_name)  
        with zipfile.ZipFile(dataset_subdir + dataset_name, "r") as zip_ref:
            zip_ref.extractall(dataset_subdir)

        with open(dataset_subdir + "info.txt", 'w') as f:
            f.write("Información estadística de los casos de COVID19 en México\n18 de agosto de 2022")
            info = info_text
            f.write(info + '\n')
            f.write("Descargado el " + datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S") + "\n")
            f.write("Desde: " + dataset_url + "\n")
            f.write("Nombre: " + dataset_name + "\n")

In [4]:
# Downloading the 3 datasets
downloading_dataset(COVID_url_1, COVID_archivo_1, subdir_1, info_1)
downloading_dataset(COVID_url_2, COVID_archivo_2, subdir_2, info_2)
downloading_dataset(COVID_url_3, COVID_archivo_3, subdir_3, info_3)

In [5]:
# Reading dataframes
df_1 = pd.read_csv('./data/COVID19_MEX_18_08_22_/220818COVID19MEXICO.csv')
df_2 = pd.read_csv('./data/COVID19_MEX_18_09_22_/220918COVID19MEXICO.csv')
df_3 = pd.read_csv('./data/COVID19_MEX_18_10_22_/221018COVID19MEXICO.csv')

c:\Users\eliud\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3444: DtypeWarning: Columns (38) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

In [6]:
df_1

,FECHA_ACTUALIZACION,ID_REGISTRO,ORIGEN,SECTOR,ENTIDAD_UM,SEXO,ENTIDAD_NAC,ENTIDAD_RES,MUNICIPIO_RES,TIPO_PACIENTE,...,OTRO_CASO,TOMA_MUESTRA_LAB,RESULTADO_LAB,TOMA_MUESTRA_ANTIGENO,RESULTADO_ANTIGENO,CLASIFICACION_FINAL,MIGRANTE,PAIS_NACIONALIDAD,PAIS_ORIGEN,UCI
0,2022-08-18,3391f0,1,6,17,1,12,17,28,1,...,1,1,2,1,2,7,99,México,97,97
1,2022-08-18,375634,1,6,9,1,15,9,7,1,...,2,2,97,1,2,7,99,México,97,97
2,2022-08-18,399f92,1,6,15,2,15,15,104,1,...,2,2,97,1,2,7,99,México,97,97
3,2022-08-18,328a5a,2,6,5,2,5,5,33,1,...,2,2,97,1,2,7,99,México,97,97
4,2022-08-18,2d077f,2,12,25,1,25,25,6,1,...,1,1,4,2,97,6,99,México,97,97
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5325950,2022-08-18,m0259bd,2,12,15,1,12,15,106,1,...,99,2,97,1,2,7,99,México,97,97
5325951,2022-08-18,m0e2e7d,2,12,15,1,30,15,999,1,...,99,2,97,1,2,7,99,México,97,97
5325952,2022-08-18,m1aa04b,2,12,15,2,15,15,999,1,...,99,2,97,1,2,7,99,México,97,97
5325953,2022-08-18,m05424c,2,12,15,1,9,15,20,1,...,99,2,97,1,2,7,99,México,97,97
5325954,2022-08-18,m0484c3,2,3,15,2,15,15,999,1,...,99,2,97,1,2,7,99,México,97,97

In [7]:
df_2

,FECHA_ACTUALIZACION,ID_REGISTRO,ORIGEN,SECTOR,ENTIDAD_UM,SEXO,ENTIDAD_NAC,ENTIDAD_RES,MUNICIPIO_RES,TIPO_PACIENTE,...,OTRO_CASO,TOMA_MUESTRA_LAB,RESULTADO_LAB,TOMA_MUESTRA_ANTIGENO,RESULTADO_ANTIGENO,CLASIFICACION_FINAL,MIGRANTE,PAIS_NACIONALIDAD,PAIS_ORIGEN,UCI
0,2022-09-18,01e27d,2,9,25,2,25,25,1,1,...,2,2,97,1,2,7,99,México,97,97
1,2022-09-18,180725,2,9,9,2,9,9,12,2,...,2,2,97,1,2,7,99,México,97,2
2,2022-09-18,0793b8,2,12,9,2,9,9,10,1,...,2,2,97,1,2,7,99,México,97,97
3,2022-09-18,1c80d5,1,6,3,1,14,3,3,1,...,2,1,1,2,97,3,99,México,97,97
4,2022-09-18,1a78cd,1,6,10,2,10,10,5,1,...,1,1,2,2,97,7,99,México,97,97
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5632612,2022-09-18,m081f3e,2,12,15,1,9,15,999,1,...,99,2,97,1,2,7,99,México,97,97
5632613,2022-09-18,m0523d2,2,12,15,1,15,15,999,1,...,99,2,97,1,2,7,99,México,97,97
5632614,2022-09-18,m1257c9,2,12,15,1,15,15,999,1,...,99,2,97,1,2,7,99,México,97,97
5632615,2022-09-18,m09e955,2,3,15,1,15,15,999,1,...,99,2,97,1,2,7,99,México,97,97
5632616,2022-09-18,m178e91,2,12,15,2,15,15,999,1,...,99,2,97,1,2,7,99,México,97,97

In [8]:
df_3

,FECHA_ACTUALIZACION,ID_REGISTRO,ORIGEN,SECTOR,ENTIDAD_UM,SEXO,ENTIDAD_NAC,ENTIDAD_RES,MUNICIPIO_RES,TIPO_PACIENTE,...,OTRO_CASO,TOMA_MUESTRA_LAB,RESULTADO_LAB,TOMA_MUESTRA_ANTIGENO,RESULTADO_ANTIGENO,CLASIFICACION_FINAL,MIGRANTE,PAIS_NACIONALIDAD,PAIS_ORIGEN,UCI
0,2022-10-18,06fce8,1,12,7,1,7,7,59,1,...,2,2,97,1,2,7,99,México,97,97
1,2022-10-18,1c80d5,1,6,3,1,14,3,3,1,...,2,1,1,2,97,3,99,México,97,97
2,2022-10-18,1e6dad,1,12,7,1,6,7,12,1,...,2,2,97,2,97,6,99,México,97,97
3,2022-10-18,0741e4,2,6,9,2,9,9,16,2,...,2,1,4,2,97,2,99,México,97,2
4,2022-10-18,10e0db,1,12,20,2,20,20,67,1,...,1,2,97,1,2,7,99,México,97,97
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5836425,2022-10-18,m1e5fc6,2,12,15,1,9,15,58,1,...,99,2,97,1,1,3,99,México,97,97
5836426,2022-10-18,m0deffa,2,12,15,1,15,15,999,1,...,99,2,97,1,2,7,99,México,97,97
5836427,2022-10-18,m074f2d,2,12,15,1,15,15,999,1,...,99,2,97,1,2,7,99,México,97,97
5836428,2022-10-18,m0a7c92,2,12,15,1,15,15,2,1,...,99,2,97,1,2,7,99,México,97,97
5836429,2022-10-18,m128007,2,12,15,1,15,15,999,1,...,99,2,97,1,2,7,99,México,97,97

# Generating tidy dataframes

In [9]:
# Concatenating all dataframes into one
df = pd.concat([df_1, df_2, df_3], axis=0)

# Dropping these columns because we won't be using them
df = df.drop(columns=['FECHA_ACTUALIZACION', 'ID_REGISTRO', 'PAIS_NACIONALIDAD','PAIS_ORIGEN'])

# Resetting index in dataframe
df = df.reset_index(drop=True)

In [12]:
df

,ORIGEN,SECTOR,ENTIDAD_UM,SEXO,ENTIDAD_NAC,ENTIDAD_RES,MUNICIPIO_RES,TIPO_PACIENTE,FECHA_INGRESO,FECHA_SINTOMAS,...,RENAL_CRONICA,TABAQUISMO,OTRO_CASO,TOMA_MUESTRA_LAB,RESULTADO_LAB,TOMA_MUESTRA_ANTIGENO,RESULTADO_ANTIGENO,CLASIFICACION_FINAL,MIGRANTE,UCI
0,1,6,17,1,12,17,28,1,2022-01-11,2022-01-09,...,2,2,1,1,2,1,2,7,99,97
1,1,6,9,1,15,9,7,1,2022-04-26,2022-04-26,...,2,2,2,2,97,1,2,7,99,97
2,1,6,15,2,15,15,104,1,2022-02-08,2022-02-05,...,2,2,2,2,97,1,2,7,99,97
3,2,6,5,2,5,5,33,1,2022-01-10,2022-01-05,...,2,2,2,2,97,1,2,7,99,97
4,2,12,25,1,25,25,6,1,2022-06-20,2022-06-17,...,2,2,1,1,4,2,97,6,99,97
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16794997,2,12,15,1,9,15,58,1,2022-09-19,2022-09-19,...,2,2,99,2,97,1,1,3,99,97
16794998,2,12,15,1,15,15,999,1,2022-09-19,2022-09-19,...,2,2,99,2,97,1,2,7,99,97
16794999,2,12,15,1,15,15,999,1,2022-09-19,2022-09-19,...,2,2,99,2,97,1,2,7,99,97
16795000,2,12,15,1,15,15,2,1,2022-09-19,2022-09-19,...,2,2,99,2,97,1,2,7,99,97
16795001,2,12,15,1,15,15,999,1,2022-09-19,2022-09-19,...,2,2,99,2,97,1,2,7,99,97

In [10]:
# Changing dates str type to datetime type
df['FECHA_INGRESO'] = pd.to_datetime(df['FECHA_INGRESO'])
df['FECHA_SINTOMAS'] = pd.to_datetime(df['FECHA_SINTOMAS'])

# 9999-99-99 is out of bounds for to_datetime so i set it to the maximum date possible
df.loc[(df['FECHA_DEF'] == '9999-99-99'),'FECHA_DEF']= '2262-04-11'
df['FECHA_DEF'] = pd.to_datetime(df['FECHA_DEF'])

In [11]:
# Checking data types in dataframe
df.dtypes

ORIGEN                            int64
SECTOR                            int64
ENTIDAD_UM                        int64
SEXO                              int64
ENTIDAD_NAC                       int64
ENTIDAD_RES                       int64
MUNICIPIO_RES                     int64
TIPO_PACIENTE                     int64
FECHA_INGRESO            datetime64[ns]
FECHA_SINTOMAS           datetime64[ns]
FECHA_DEF                datetime64[ns]
INTUBADO                          int64
NEUMONIA                          int64
EDAD                              int64
NACIONALIDAD                      int64
EMBARAZO                          int64
HABLA_LENGUA_INDIG                int64
INDIGENA                          int64
DIABETES                          int64
EPOC                              int64
ASMA                              int64
INMUSUPR                          int64
HIPERTENSION                      int64
OTRA_COM                          int64
CARDIOVASCULAR                    int64
OBESIDAD                          int64
RENAL_CRONICA                     int64
TABAQUISMO                        int64
OTRO_CASO                         int64
TOMA_MUESTRA_LAB                  int64
RESULTADO_LAB                     int64
TOMA_MUESTRA_ANTIGENO             int64
RESULTADO_ANTIGENO                int64
CLASIFICACION_FINAL               int64
MIGRANTE                          int64
UCI                               int64
dtype: object

In [12]:
# Final dataframe
df

,ORIGEN,SECTOR,ENTIDAD_UM,SEXO,ENTIDAD_NAC,ENTIDAD_RES,MUNICIPIO_RES,TIPO_PACIENTE,FECHA_INGRESO,FECHA_SINTOMAS,...,RENAL_CRONICA,TABAQUISMO,OTRO_CASO,TOMA_MUESTRA_LAB,RESULTADO_LAB,TOMA_MUESTRA_ANTIGENO,RESULTADO_ANTIGENO,CLASIFICACION_FINAL,MIGRANTE,UCI
0,1,6,17,1,12,17,28,1,2022-01-11,2022-01-09,...,2,2,1,1,2,1,2,7,99,97
1,1,6,9,1,15,9,7,1,2022-04-26,2022-04-26,...,2,2,2,2,97,1,2,7,99,97
2,1,6,15,2,15,15,104,1,2022-02-08,2022-02-05,...,2,2,2,2,97,1,2,7,99,97
3,2,6,5,2,5,5,33,1,2022-01-10,2022-01-05,...,2,2,2,2,97,1,2,7,99,97
4,2,12,25,1,25,25,6,1,2022-06-20,2022-06-17,...,2,2,1,1,4,2,97,6,99,97
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16794997,2,12,15,1,9,15,58,1,2022-09-19,2022-09-19,...,2,2,99,2,97,1,1,3,99,97
16794998,2,12,15,1,15,15,999,1,2022-09-19,2022-09-19,...,2,2,99,2,97,1,2,7,99,97
16794999,2,12,15,1,15,15,999,1,2022-09-19,2022-09-19,...,2,2,99,2,97,1,2,7,99,97
16795000,2,12,15,1,15,15,2,1,2022-09-19,2022-09-19,...,2,2,99,2,97,1,2,7,99,97
16795001,2,12,15,1,15,15,999,1,2022-09-19,2022-09-19,...,2,2,99,2,97,1,2,7,99,97